version: "3.9"

volumes:
  pgdata:
    driver: local

services:
  rentx-database:
    image: postgres
    container_name: rentx-database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: rentx
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - rentx-database
    depends_on:
      - rentx-database
